name: Docker Build and Push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn clean package
          find ./practice_4/exercise_1/target -name 'exercise_1-*.jar' | xargs -I '{}' mv -v {} ./docker/practice_4/exercise_1/app.jar
          find ./practice_4/exercise_2/target -name 'exercise_2-*.jar' | xargs -I '{}' mv -v {} ./docker/practice_4/exercise_2/app.jar
          find ./practice_4/exercise_3/target -name 'exercise_3-*.jar' | xargs -I '{}' mv -v {} ./docker/practice_4/exercise_3/app.jar
          find ./practice_5/target -name 'practice_5-*.jar' | xargs -I '{}' mv -v {} ./docker/practice_5/app.jar

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Practice-4/Exercise-1 Image and Push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker:practice_4:exercise_1"
          file: ./docker/practice_4/exercise_1/Dockerfile
          push: true
          tags: daniilb/tsi-java-practice-4-exercise-1:latest

      - name: Build Practice-4/Exercise-2 Image and Push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker:practice_4:exercise_2"
          file: ./docker/practice_4/exercise_2/Dockerfile
          push: true
          tags: daniilb/tsi-java-practice-4-exercise-2:latest

      - name: Build Practice-4/Exercise-3 Image and Push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker:practice_4:exercise_3"
          file: ./docker/practice_4/exercise_3/Dockerfile
          push: true
          tags: daniilb/tsi-java-practice-4-exercise-3:latest

      - name: Build Practice-5 Image and Push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker:practice_5"
          file: ./docker/practice_5/Dockerfile
          push: true
          tags: daniilb/tsi-java-practice-5:latest
